Feature/task1
kuanyshtokanov/stellar pull request #1
Opened 2020-12-10 12:34 UTC by kuanyshtokanov

2020-12-10 15:29 UTC, kuanyshtokanov commented
Страница находится здесь - /about

2020-12-14 13:30 UTC, veronicazh commented on components/Header/index.styl
> +  margin-bottom 4u
не нужен, у этого элемента нет соседа снизу. увеличь паддинг у рута

2020-12-14 13:45 UTC, veronicazh commented on main/pages/PAbout/index.styl
> +.container
тут бы не помешал padding слева и справа по 2u

2020-12-14 13:52 UTC, veronicazh commented on components/Main/Intro/index.styl
> +  margin-bottom 4u
не нужен

2020-12-14 13:54 UTC, veronicazh commented on components/Main/First/index.styl
> +  margin-bottom 3u
не нужен, нет соседа снизу. если нужен большой отступ, увеличь margin-bottom у .first

2020-12-14 13:59 UTC, veronicazh commented on components/Main/First/index.styl
> +  margin-bottom 3u
не нужен

2020-12-14 14:02 UTC, veronicazh commented on components/Footer/index.styl
> +  line-height 6u
это много. 4u. отступ от соседних элементов за счет line-height лучше не делать, юзай margin

2020-12-14 14:05 UTC, veronicazh commented on components/Footer/index.js
> +          View.copyright
один и тот же класс .copyright тут и на строке 28. сюда применяются стили, которые тут не нужны. надо переименовать.

2020-12-14 14:14 UTC, veronicazh commented on components/Main/index.js
> +      Section(intro)
прокинь сюда first, чтобы на мобилке убрался верхний бордер (у тебя это прописано в стилях в Section), а в .navBar там же юзай только нижний бордер

2020-12-14 14:30 UTC, veronicazh commented on components/Main/Section/index.styl
> +    border-top 0
у навБара должен быть сверху border-radius

2020-12-14 14:37 UTC, veronicazh commented on components/Main/Section/index.styl
> +     padding 8u 6u 4u
![image](https://user-images.githubusercontent.com/35896728/102094134-a3a54d00-3e2a-11eb-980b-daea59d5867b.png)
следи, чтобы на всех брейкпоинтах был одинаковый ритм. тут например сейчас разный верхний и нижний padding

2020-12-14 14:41 UTC, veronicazh commented on components/Button/index.js
> +      View.btn(styleName=[{ info, action }])
![image](https://user-images.githubusercontent.com/35896728/102094548-23331c00-3e2b-11eb-9395-74228097365c.png)
на таблете в футере кнопка не должна быть растянута по всей ширине

2020-12-14 14:44 UTC, veronicazh commented on components/Main/First/index.js
> +  return pug`
![image](https://user-images.githubusercontent.com/35896728/102094936-92107500-3e2b-11eb-9004-0b1783c502bc.png)
на десктопе элементы должны стоять в ряд

2021-01-29 10:43 UTC, lupenq requested changes

2021-01-29 10:43 UTC, lupenq commented on components/Footer/index.styl
> +  display flex
В react native display flex по умолчанию у всех элементов

2021-01-29 10:43 UTC, lupenq commented on components/Main/First/index.js
> +          Text.txt #{item.text}
Мы придерживаемся такого стиля:
Text.txt= item.text

2021-01-29 10:43 UTC, lupenq commented on components/Header/index.styl
> +  border-radius 50%
в реакт нейтив нельзя использовать % дня   border-radius

2021-01-29 10:43 UTC, lupenq commented on components/Main/Section/index.js
> +    View.section(styleName=[{ first, intro, navBar }]) #{children}
стринга не может быть чилдом для View

2021-02-09 11:47 UTC, ssstelsss requested changes

2021-02-09 11:47 UTC, ssstelsss commented on components/Button/index.styl
> +  // +wide()
коменты поубирай

2021-02-09 11:47 UTC, ssstelsss commented on components/ContactInfo/index.styl
> +  border-bottom dotted 1px
dotted вроде раньше не работал на андроиде, проверял?

2021-02-09 11:47 UTC, ssstelsss commented on components/Link/index.js
> +    TouchableOpacity(onPress=handleClick styleName=[{active}]) #{children}
)= children

2021-02-09 11:47 UTC, ssstelsss commented on components/Link/index.js
> +    TouchableOpacity(onPress=handleClick styleName=[{active}]) #{children}
styleName={active}

2021-02-09 11:47 UTC, ssstelsss commented on components/Main/Cta/index.js
> +
лишний отступ

2021-02-09 11:47 UTC, ssstelsss commented on components/Main/First/index.styl
> +    width calc(50% - 6u)
давай перепишем это без calc

2021-02-09 11:47 UTC, ssstelsss commented on components/Main/Intro/index.styl
> +  flex 0 1 auto
flex 1

2021-02-09 11:47 UTC, ssstelsss commented on components/Main/Second/index.js
> +      Text.txt(style={color: '#636363'}) Donec imperdiet consequat consequat. Suspendisse feugiat congue posuere. Nulla massa urna, fermentum eget quam aliquet.
давай стили перенесем в файл стилей

2021-02-09 11:47 UTC, ssstelsss commented on components/Main/Second/index.styl
> +    width: 20%
: лишнее, посмотри все стили на предмет этого

2021-02-09 11:47 UTC, ssstelsss commented on components/Row/index.styl
> +  flex-grow 0
flex-grow 0 точно неужен?

2021-02-09 11:47 UTC, ssstelsss commented on model/TestThingModel.js
> +    console.log('asd', this.getId())
логи не нужны

2021-04-28 13:23 UTC, merged